Tree by chromosome
joshuak94/BAMIntervalTree pull request #25
Opened 2021-04-15 18:08 UTC by joshuak94

Create one interval tree per chromosome.

Currently a work in progress, don't merge yet!

2021-04-16 13:24 UTC, MitraDarja requested changes
LGTM, just some minor things about the docu and please fix the doc error from the CI. :)

2021-04-16 13:24 UTC, MitraDarja commented on include/bamit/IntervalNode.hpp
> +            // Start at given start only for the first chromosome, otherwise start searching from 0.
Mabye add explaination why.

2021-04-16 13:24 UTC, MitraDarja commented on include/bamit/IntervalNode.hpp
> +            // If we find the left-most offset we can stop. Otherwise we have to check the next tree.
Add if the given interval spans more than one chromosome, right?

2021-04-16 13:24 UTC, MitraDarja commented on test/api/search_test.cpp
> +    // Permanent fix: seqan3 is changing how you get/use the file position.
Is the test file the best place to mention this problem? Should be in the include file and maybe add a #TODO or something?

2021-04-20 08:34 UTC, joshuak94 commented
@MitraDarja I made a few changes since the last time, can you look again.

2021-04-20 13:18 UTC, MitraDarja approved these changes

2021-04-21 08:13 UTC, merged