Fix bugs related to read lengths.
joshuak94/BAMIntervalTree pull request #43
Opened 2022-03-07 11:32 UTC by joshuak94

Fixed two bugs:
1. Previously, we were updating the node's end position with every record parsed, not considering a record might end *before* the previous record ends. Now it only stores the end if it's after the current end.
2. Previously weren't filtering reads out for overlap queries which were in the node but not intersecting the query itself.

2022-03-07 12:29 UTC, joshuak94 commented
@eseiler Do you know why the following gives an error on gcc10:
```cpp
                              | std::views::filter([start](auto & rec) {return !unmapped(rec);})
                              | std::views::filter([start](auto & rec) {return std::make_tuple(rec.reference_id().value(), get_length((rec).cigar_sequence()) + rec.reference_position().value()) >= start;})
```cpp

But then this doesn't:
```cpp
                              | std::views::filter([start](auto & rec) {return !unmapped(rec) && std::make_tuple(rec.reference_id().value(), get_length((rec).cigar_sequence()) + rec.reference_position().value()) >= start;})
```

2022-03-07 13:12 UTC, eseiler commented
I'm not sure, probably some quirk :D

The second version is better anyway, since you only need to create one filter, and the condition is short-circuited, i.e., if `!unmapped(rec)` is false, the rest is not evaluated.

2022-03-07 13:53 UTC, Irallia requested changes
As far as I understand it, it looks very good. I'm just unsure about the description, if you didn't adjust it the other way around.

2022-03-07 13:53 UTC, Irallia commented on include/bamit/IntervalNode.hpp
> +    // when searching for interval 160 - 200, Read 2 will be included in results.
Isn't your description describing the bug, and the following is what you want to say?:
```suggestion
    // when searching for interval 160 - 200, Read 2 will not be included in results, as it is outside the query range.
```

2022-03-09 09:21 UTC, Irallia approved these changes

2022-03-16 14:15 UTC, merged